# Generated by Django 4.0.5 on 2022-07-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('fullnane', models.CharField(max_length=50)),
                ('standard', models.CharField(max_length=50)),
            ],
        ),
    ]
