# Generated by Django 4.0.5 on 2022-07-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_1', '0003_rename_fullnane_student_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
    ]
